// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/application.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Application defines the Application message.
type Application struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GigId         uint64 `protobuf:"varint,2,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	Freelancer    string `protobuf:"bytes,3,opt,name=freelancer,proto3" json:"freelancer,omitempty"`
	CoverLetter   string `protobuf:"bytes,4,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	ProposedPrice uint64 `protobuf:"varint,5,opt,name=proposed_price,json=proposedPrice,proto3" json:"proposed_price,omitempty"`
	ProposedDays  uint64 `protobuf:"varint,6,opt,name=proposed_days,json=proposedDays,proto3" json:"proposed_days,omitempty"`
	Status        string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Creator       string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed954d196966b03a, []int{0}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Application.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return m.Size()
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetGigId() uint64 {
	if m != nil {
		return m.GigId
	}
	return 0
}

func (m *Application) GetFreelancer() string {
	if m != nil {
		return m.Freelancer
	}
	return ""
}

func (m *Application) GetCoverLetter() string {
	if m != nil {
		return m.CoverLetter
	}
	return ""
}

func (m *Application) GetProposedPrice() uint64 {
	if m != nil {
		return m.ProposedPrice
	}
	return 0
}

func (m *Application) GetProposedDays() uint64 {
	if m != nil {
		return m.ProposedDays
	}
	return 0
}

func (m *Application) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Application) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Application) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Application)(nil), "skillchain.marketplace.v1.Application")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/application.proto", fileDescriptor_ed954d196966b03a)
}

var fileDescriptor_ed954d196966b03a = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xb1, 0x4a, 0x43, 0x31,
	0x14, 0x06, 0xe0, 0xe6, 0xb6, 0xbd, 0xb5, 0xa7, 0xb5, 0x43, 0x40, 0x89, 0x83, 0xa1, 0x2a, 0x42,
	0x41, 0x68, 0x29, 0x2e, 0xae, 0x15, 0x17, 0xc1, 0x41, 0x3a, 0xba, 0x5c, 0x62, 0x72, 0xbc, 0x86,
	0xc6, 0x26, 0x24, 0xb1, 0xd8, 0xb7, 0x70, 0xf0, 0xa1, 0x1c, 0x3b, 0x3a, 0x4a, 0xfb, 0x22, 0x62,
	0x68, 0x6d, 0x1d, 0xff, 0x8f, 0xff, 0x70, 0xe0, 0x87, 0x8b, 0x30, 0xd1, 0xc6, 0xc8, 0x67, 0xa1,
	0xa7, 0x83, 0x17, 0xe1, 0x27, 0x18, 0x9d, 0x11, 0x12, 0x07, 0xb3, 0xe1, 0x40, 0x38, 0x67, 0xb4,
	0x14, 0x51, 0xdb, 0x69, 0xdf, 0x79, 0x1b, 0x2d, 0x3d, 0xda, 0x96, 0xfb, 0x3b, 0xe5, 0xfe, 0x6c,
	0x78, 0xfa, 0x91, 0x41, 0x6b, 0xb4, 0x3d, 0xa0, 0x1d, 0xc8, 0xb4, 0x62, 0xa4, 0x4b, 0x7a, 0xb5,
	0x71, 0xa6, 0x15, 0x3d, 0x80, 0xbc, 0xd4, 0x65, 0xa1, 0x15, 0xcb, 0x92, 0xd5, 0x4b, 0x5d, 0xde,
	0x2a, 0xca, 0x01, 0x9e, 0x3c, 0xa2, 0x11, 0x53, 0x89, 0x9e, 0x55, 0xbb, 0xa4, 0xd7, 0x1c, 0xef,
	0x08, 0x3d, 0x81, 0xb6, 0xb4, 0x33, 0xf4, 0x85, 0xc1, 0x18, 0xd1, 0xb3, 0x5a, 0x6a, 0xb4, 0x92,
	0xdd, 0x25, 0xa2, 0xe7, 0xd0, 0x71, 0xde, 0x3a, 0x1b, 0x50, 0x15, 0xce, 0x6b, 0x89, 0xac, 0x9e,
	0x3e, 0xec, 0x6f, 0xf4, 0xfe, 0x17, 0xe9, 0x19, 0xfc, 0x41, 0xa1, 0xc4, 0x3c, 0xb0, 0x3c, 0xb5,
	0xda, 0x1b, 0xbc, 0x11, 0xf3, 0x40, 0x0f, 0x21, 0x0f, 0x51, 0xc4, 0xd7, 0xc0, 0x1a, 0xe9, 0xd1,
	0x3a, 0xd1, 0x63, 0x00, 0xe9, 0x51, 0x44, 0x54, 0x85, 0x88, 0x6c, 0xaf, 0x4b, 0x7a, 0xd5, 0x71,
	0x73, 0x2d, 0xa3, 0x48, 0x19, 0x34, 0x52, 0xb0, 0x9e, 0x35, 0xd3, 0xdd, 0x26, 0x5e, 0x5f, 0x7d,
	0x2e, 0x39, 0x59, 0x2c, 0x39, 0xf9, 0x5e, 0x72, 0xf2, 0xbe, 0xe2, 0x95, 0xc5, 0x8a, 0x57, 0xbe,
	0x56, 0xbc, 0xf2, 0xc0, 0x77, 0x86, 0x7f, 0xfb, 0x37, 0x7d, 0x9c, 0x3b, 0x0c, 0x8f, 0x79, 0x9a,
	0xfc, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x55, 0x04, 0xbf, 0xa1, 0x01, 0x00, 0x00,
}

func (m *Application) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Application) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Application) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintApplication(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintApplication(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintApplication(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ProposedDays != 0 {
		i = encodeVarintApplication(dAtA, i, uint64(m.ProposedDays))
		i--
		dAtA[i] = 0x30
	}
	if m.ProposedPrice != 0 {
		i = encodeVarintApplication(dAtA, i, uint64(m.ProposedPrice))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CoverLetter) > 0 {
		i -= len(m.CoverLetter)
		copy(dAtA[i:], m.CoverLetter)
		i = encodeVarintApplication(dAtA, i, uint64(len(m.CoverLetter)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Freelancer) > 0 {
		i -= len(m.Freelancer)
		copy(dAtA[i:], m.Freelancer)
		i = encodeVarintApplication(dAtA, i, uint64(len(m.Freelancer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.GigId != 0 {
		i = encodeVarintApplication(dAtA, i, uint64(m.GigId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintApplication(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApplication(dAtA []byte, offset int, v uint64) int {
	offset -= sovApplication(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Application) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovApplication(uint64(m.Id))
	}
	if m.GigId != 0 {
		n += 1 + sovApplication(uint64(m.GigId))
	}
	l = len(m.Freelancer)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	l = len(m.CoverLetter)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	if m.ProposedPrice != 0 {
		n += 1 + sovApplication(uint64(m.ProposedPrice))
	}
	if m.ProposedDays != 0 {
		n += 1 + sovApplication(uint64(m.ProposedDays))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovApplication(uint64(m.CreatedAt))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	return n
}

func sovApplication(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApplication(x uint64) (n int) {
	return sovApplication(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Application) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Application: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Application: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GigId", wireType)
			}
			m.GigId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GigId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Freelancer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Freelancer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoverLetter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoverLetter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedPrice", wireType)
			}
			m.ProposedPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposedPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedDays", wireType)
			}
			m.ProposedDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposedDays |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApplication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApplication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApplication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApplication(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApplication
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApplication
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApplication
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApplication
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApplication        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApplication          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApplication = fmt.Errorf("proto: unexpected end of group")
)
