// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/contract.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Contract defines the Contract message.
type Contract struct {
	Id               uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GigId            uint64 `protobuf:"varint,2,opt,name=gig_id,json=gigId,proto3" json:"gig_id,omitempty"`
	ApplicationId    uint64 `protobuf:"varint,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Client           string `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Freelancer       string `protobuf:"bytes,5,opt,name=freelancer,proto3" json:"freelancer,omitempty"`
	Price            uint64 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	DeliveryDeadline int64  `protobuf:"varint,7,opt,name=delivery_deadline,json=deliveryDeadline,proto3" json:"delivery_deadline,omitempty"`
	Status           string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt      int64  `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Creator          string `protobuf:"bytes,11,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_4509a2873347ab9e, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return m.Size()
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contract) GetGigId() uint64 {
	if m != nil {
		return m.GigId
	}
	return 0
}

func (m *Contract) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Contract) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Contract) GetFreelancer() string {
	if m != nil {
		return m.Freelancer
	}
	return ""
}

func (m *Contract) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Contract) GetDeliveryDeadline() int64 {
	if m != nil {
		return m.DeliveryDeadline
	}
	return 0
}

func (m *Contract) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Contract) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Contract) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

func (m *Contract) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Contract)(nil), "skillchain.marketplace.v1.Contract")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/contract.proto", fileDescriptor_4509a2873347ab9e)
}

var fileDescriptor_4509a2873347ab9e = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4f, 0x22, 0x31,
	0x18, 0x86, 0xe9, 0x00, 0x03, 0x7c, 0xec, 0x92, 0xdd, 0x66, 0xd7, 0xd4, 0x83, 0x0d, 0x9a, 0x98,
	0x4c, 0x62, 0x02, 0x21, 0x5e, 0xbc, 0xa2, 0x5e, 0xb8, 0x72, 0xf4, 0x42, 0x6a, 0xfb, 0x39, 0x36,
	0x94, 0x99, 0xa6, 0x53, 0x89, 0xfc, 0x0b, 0xff, 0x95, 0x1e, 0x39, 0x7a, 0x34, 0xf0, 0x47, 0x0c,
	0x65, 0xd0, 0xf1, 0xf8, 0x3e, 0xef, 0xd3, 0x7e, 0x87, 0x17, 0x92, 0x62, 0xae, 0x8d, 0x91, 0x8f,
	0x42, 0x67, 0xc3, 0x85, 0x70, 0x73, 0xf4, 0xd6, 0x08, 0x89, 0xc3, 0xe5, 0x68, 0x28, 0xf3, 0xcc,
	0x3b, 0x21, 0xfd, 0xc0, 0xba, 0xdc, 0xe7, 0xf4, 0xf8, 0xdb, 0x1c, 0x54, 0xcc, 0xc1, 0x72, 0x74,
	0xf6, 0x1a, 0x41, 0xfb, 0xa6, 0xb4, 0x69, 0x0f, 0x22, 0xad, 0x18, 0xe9, 0x93, 0xa4, 0x31, 0x8d,
	0xb4, 0xa2, 0xff, 0x21, 0x4e, 0x75, 0x3a, 0xd3, 0x8a, 0x45, 0x81, 0x35, 0x53, 0x9d, 0x4e, 0x14,
	0x3d, 0x87, 0x9e, 0xb0, 0xd6, 0x68, 0x29, 0xbc, 0xce, 0xb3, 0x5d, 0x5d, 0x0f, 0xf5, 0xef, 0x0a,
	0x9d, 0x28, 0x7a, 0x04, 0xb1, 0x34, 0x1a, 0x33, 0xcf, 0x1a, 0x7d, 0x92, 0x74, 0xa6, 0x65, 0xa2,
	0x1c, 0xe0, 0xc1, 0x21, 0x1a, 0x91, 0x49, 0x74, 0xac, 0x19, 0xba, 0x0a, 0xa1, 0xff, 0xa0, 0x69,
	0x9d, 0x96, 0xc8, 0xe2, 0xfd, 0xd1, 0x10, 0xe8, 0x05, 0xfc, 0x55, 0x68, 0xf4, 0x12, 0xdd, 0x6a,
	0xa6, 0x50, 0x28, 0xa3, 0x33, 0x64, 0xad, 0x3e, 0x49, 0xea, 0xd3, 0x3f, 0x87, 0xe2, 0xb6, 0xe4,
	0xbb, 0xd3, 0x85, 0x17, 0xfe, 0xa9, 0x60, 0xed, 0xfd, 0xe9, 0x7d, 0xa2, 0x27, 0x00, 0xd2, 0xa1,
	0xf0, 0xa8, 0x66, 0xc2, 0xb3, 0x4e, 0x78, 0xdd, 0x29, 0xc9, 0xd8, 0xd3, 0x53, 0xf8, 0x25, 0xf3,
	0x85, 0x35, 0x58, 0x0a, 0x10, 0x84, 0xee, 0x17, 0x1b, 0x7b, 0xca, 0xa0, 0x15, 0xfc, 0xdc, 0xb1,
	0x6e, 0xf8, 0xfa, 0x10, 0xaf, 0xaf, 0xde, 0x36, 0x9c, 0xac, 0x37, 0x9c, 0x7c, 0x6c, 0x38, 0x79,
	0xd9, 0xf2, 0xda, 0x7a, 0xcb, 0x6b, 0xef, 0x5b, 0x5e, 0xbb, 0xe3, 0x95, 0xa1, 0x9e, 0x7f, 0x4c,
	0xe5, 0x57, 0x16, 0x8b, 0xfb, 0x38, 0xac, 0x74, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xa4,
	0xee, 0x8f, 0xd1, 0x01, 0x00, 0x00,
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x5a
	}
	if m.CompletedAt != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedAt != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x42
	}
	if m.DeliveryDeadline != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.DeliveryDeadline))
		i--
		dAtA[i] = 0x38
	}
	if m.Price != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Freelancer) > 0 {
		i -= len(m.Freelancer)
		copy(dAtA[i:], m.Freelancer)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Freelancer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Client) > 0 {
		i -= len(m.Client)
		copy(dAtA[i:], m.Client)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Client)))
		i--
		dAtA[i] = 0x22
	}
	if m.ApplicationId != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x18
	}
	if m.GigId != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.GigId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintContract(dAtA []byte, offset int, v uint64) int {
	offset -= sovContract(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovContract(uint64(m.Id))
	}
	if m.GigId != 0 {
		n += 1 + sovContract(uint64(m.GigId))
	}
	if m.ApplicationId != 0 {
		n += 1 + sovContract(uint64(m.ApplicationId))
	}
	l = len(m.Client)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Freelancer)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovContract(uint64(m.Price))
	}
	if m.DeliveryDeadline != 0 {
		n += 1 + sovContract(uint64(m.DeliveryDeadline))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovContract(uint64(m.CreatedAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovContract(uint64(m.CompletedAt))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	return n
}

func sovContract(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContract(x uint64) (n int) {
	return sovContract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GigId", wireType)
			}
			m.GigId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GigId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Client", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Client = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Freelancer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Freelancer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliveryDeadline", wireType)
			}
			m.DeliveryDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliveryDeadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContract
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContract
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContract
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContract        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContract          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContract = fmt.Errorf("proto: unexpected end of group")
)
