// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/genesis.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the marketplace module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params           Params        `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ProfileMap       []Profile     `protobuf:"bytes,2,rep,name=profile_map,json=profileMap,proto3" json:"profile_map"`
	GigList          []Gig         `protobuf:"bytes,3,rep,name=gig_list,json=gigList,proto3" json:"gig_list"`
	GigCount         uint64        `protobuf:"varint,4,opt,name=gig_count,json=gigCount,proto3" json:"gig_count,omitempty"`
	ApplicationList  []Application `protobuf:"bytes,5,rep,name=application_list,json=applicationList,proto3" json:"application_list"`
	ApplicationCount uint64        `protobuf:"varint,6,opt,name=application_count,json=applicationCount,proto3" json:"application_count,omitempty"`
	ContractList     []Contract    `protobuf:"bytes,7,rep,name=contract_list,json=contractList,proto3" json:"contract_list"`
	ContractCount    uint64        `protobuf:"varint,8,opt,name=contract_count,json=contractCount,proto3" json:"contract_count,omitempty"`
	DisputeList      []Dispute     `protobuf:"bytes,9,rep,name=dispute_list,json=disputeList,proto3" json:"dispute_list"`
	DisputeCount     uint64        `protobuf:"varint,10,opt,name=dispute_count,json=disputeCount,proto3" json:"dispute_count,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd644ff2113776b0, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetProfileMap() []Profile {
	if m != nil {
		return m.ProfileMap
	}
	return nil
}

func (m *GenesisState) GetGigList() []Gig {
	if m != nil {
		return m.GigList
	}
	return nil
}

func (m *GenesisState) GetGigCount() uint64 {
	if m != nil {
		return m.GigCount
	}
	return 0
}

func (m *GenesisState) GetApplicationList() []Application {
	if m != nil {
		return m.ApplicationList
	}
	return nil
}

func (m *GenesisState) GetApplicationCount() uint64 {
	if m != nil {
		return m.ApplicationCount
	}
	return 0
}

func (m *GenesisState) GetContractList() []Contract {
	if m != nil {
		return m.ContractList
	}
	return nil
}

func (m *GenesisState) GetContractCount() uint64 {
	if m != nil {
		return m.ContractCount
	}
	return 0
}

func (m *GenesisState) GetDisputeList() []Dispute {
	if m != nil {
		return m.DisputeList
	}
	return nil
}

func (m *GenesisState) GetDisputeCount() uint64 {
	if m != nil {
		return m.DisputeCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "skillchain.marketplace.v1.GenesisState")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/genesis.proto", fileDescriptor_bd644ff2113776b0)
}

var fileDescriptor_bd644ff2113776b0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x8e, 0xd3, 0x40,
	0x10, 0x87, 0x6d, 0xce, 0xe4, 0x2e, 0xeb, 0x1c, 0x70, 0x16, 0x85, 0x09, 0xd2, 0x12, 0x2e, 0xe2,
	0xb0, 0x38, 0xc9, 0xd6, 0x85, 0x86, 0x0e, 0x91, 0x44, 0x8a, 0x10, 0x7f, 0x84, 0x42, 0x81, 0x44,
	0x13, 0x2d, 0xc6, 0x2c, 0xab, 0xd8, 0xde, 0x95, 0xbd, 0x89, 0xe0, 0x2d, 0x78, 0x0c, 0x4a, 0x1e,
	0x23, 0x65, 0x4a, 0x2a, 0x84, 0x92, 0x82, 0x86, 0x87, 0x40, 0xde, 0x1d, 0x27, 0xa6, 0xb0, 0xd3,
	0x44, 0x1b, 0xeb, 0x9b, 0xdf, 0x37, 0x3b, 0x3b, 0xe8, 0x61, 0x3e, 0x67, 0x71, 0x1c, 0x7e, 0x26,
	0x2c, 0x0d, 0x12, 0x92, 0xcd, 0x23, 0x29, 0x62, 0x12, 0x46, 0xc1, 0xf2, 0x2a, 0xa0, 0x51, 0x1a,
	0xe5, 0x2c, 0xf7, 0x45, 0xc6, 0x25, 0x77, 0xee, 0xec, 0x41, 0xbf, 0x02, 0xfa, 0xcb, 0xab, 0xee,
	0x19, 0x49, 0x58, 0xca, 0x03, 0xf5, 0xab, 0xe9, 0xee, 0x6d, 0xca, 0x29, 0x57, 0xc7, 0xa0, 0x38,
	0xc1, 0xd7, 0xcb, 0x7a, 0x19, 0x11, 0x22, 0x66, 0x21, 0x91, 0x8c, 0xa7, 0x00, 0x7b, 0xf5, 0x70,
	0xc8, 0x53, 0x99, 0x91, 0x50, 0x02, 0xd9, 0x6f, 0xb8, 0x03, 0xa3, 0x00, 0x5d, 0xd4, 0x43, 0x82,
	0x64, 0x24, 0x81, 0x7b, 0x76, 0x1b, 0x06, 0x22, 0x32, 0xfe, 0x89, 0xc5, 0xd1, 0x61, 0xf0, 0x23,
	0xcb, 0xc5, 0x42, 0x02, 0x78, 0xfe, 0xd7, 0x42, 0x9d, 0x89, 0x9e, 0xe5, 0x5b, 0x49, 0x64, 0xe4,
	0x8c, 0x51, 0x4b, 0x2b, 0x5d, 0xb3, 0x67, 0x7a, 0xf6, 0xe0, 0xbe, 0x5f, 0x3b, 0x5b, 0xff, 0x8d,
	0x02, 0x87, 0xed, 0xd5, 0xaf, 0x7b, 0xc6, 0xf7, 0x3f, 0x3f, 0x1e, 0x99, 0x53, 0xa8, 0x75, 0x9e,
	0x23, 0x1b, 0x1a, 0x9a, 0x25, 0x44, 0xb8, 0xd7, 0x7a, 0x47, 0x9e, 0x3d, 0x38, 0x6f, 0x8a, 0xd2,
	0xf4, 0xd0, 0x2a, 0xb2, 0xa6, 0x08, 0x8a, 0x5f, 0x11, 0xe1, 0x3c, 0x45, 0x27, 0x94, 0xd1, 0x59,
	0xcc, 0x72, 0xe9, 0x1e, 0xa9, 0x1c, 0xdc, 0x90, 0x33, 0x61, 0x14, 0x32, 0x8e, 0x29, 0xa3, 0x2f,
	0x59, 0x2e, 0x9d, 0xbb, 0xa8, 0x5d, 0x04, 0x84, 0x7c, 0x91, 0x4a, 0xd7, 0xea, 0x99, 0x9e, 0x35,
	0x2d, 0x12, 0x47, 0xc5, 0x7f, 0xe7, 0x1d, 0xba, 0x55, 0x79, 0x5d, 0x6d, 0xb9, 0xae, 0x2c, 0x17,
	0x0d, 0x96, 0x67, 0xfb, 0x12, 0xb0, 0xdd, 0xac, 0xa4, 0x28, 0xeb, 0x25, 0x3a, 0xab, 0x06, 0x6b,
	0x7b, 0x4b, 0xd9, 0xab, 0x46, 0xdd, 0xc5, 0x6b, 0x74, 0x5a, 0xae, 0x8d, 0x6e, 0xe1, 0x58, 0xb5,
	0xd0, 0x6f, 0x68, 0x61, 0x04, 0x3c, 0xf8, 0x3b, 0x65, 0xbd, 0x92, 0x3f, 0x40, 0x37, 0x76, 0x79,
	0xda, 0x7c, 0xa2, 0xcc, 0x3b, 0x8b, 0xd6, 0xbe, 0x40, 0x1d, 0xd8, 0x06, 0x6d, 0x6d, 0x1f, 0x7c,
	0xa6, 0xb1, 0xc6, 0x41, 0x6a, 0x43, 0xb5, 0x72, 0xf6, 0xd1, 0x69, 0x19, 0xa6, 0x95, 0x48, 0x29,
	0x4b, 0x83, 0x32, 0x0e, 0x9f, 0xac, 0x36, 0xd8, 0x5c, 0x6f, 0xb0, 0xf9, 0x7b, 0x83, 0xcd, 0x6f,
	0x5b, 0x6c, 0xac, 0xb7, 0xd8, 0xf8, 0xb9, 0xc5, 0xc6, 0x7b, 0x5c, 0xd9, 0xd8, 0x2f, 0xff, 0xed,
	0xac, 0xfc, 0x2a, 0xa2, 0xfc, 0x43, 0x4b, 0xed, 0xeb, 0xe3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd8, 0xeb, 0x37, 0x4e, 0x14, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DisputeCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DisputeCount))
		i--
		dAtA[i] = 0x50
	}
	if len(m.DisputeList) > 0 {
		for iNdEx := len(m.DisputeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DisputeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.ContractCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ContractCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ContractList) > 0 {
		for iNdEx := len(m.ContractList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.ApplicationCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ApplicationCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ApplicationList) > 0 {
		for iNdEx := len(m.ApplicationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApplicationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.GigCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GigCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.GigList) > 0 {
		for iNdEx := len(m.GigList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GigList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ProfileMap) > 0 {
		for iNdEx := len(m.ProfileMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProfileMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ProfileMap) > 0 {
		for _, e := range m.ProfileMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GigList) > 0 {
		for _, e := range m.GigList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GigCount != 0 {
		n += 1 + sovGenesis(uint64(m.GigCount))
	}
	if len(m.ApplicationList) > 0 {
		for _, e := range m.ApplicationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ApplicationCount != 0 {
		n += 1 + sovGenesis(uint64(m.ApplicationCount))
	}
	if len(m.ContractList) > 0 {
		for _, e := range m.ContractList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ContractCount != 0 {
		n += 1 + sovGenesis(uint64(m.ContractCount))
	}
	if len(m.DisputeList) > 0 {
		for _, e := range m.DisputeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DisputeCount != 0 {
		n += 1 + sovGenesis(uint64(m.DisputeCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfileMap = append(m.ProfileMap, Profile{})
			if err := m.ProfileMap[len(m.ProfileMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GigList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GigList = append(m.GigList, Gig{})
			if err := m.GigList[len(m.GigList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GigCount", wireType)
			}
			m.GigCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GigCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationList = append(m.ApplicationList, Application{})
			if err := m.ApplicationList[len(m.ApplicationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationCount", wireType)
			}
			m.ApplicationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractList = append(m.ContractList, Contract{})
			if err := m.ContractList[len(m.ContractList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractCount", wireType)
			}
			m.ContractCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisputeList = append(m.DisputeList, Dispute{})
			if err := m.DisputeList[len(m.DisputeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeCount", wireType)
			}
			m.DisputeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
