// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/gig.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Gig defines the Gig message.
type Gig struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owner        string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Price        uint64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Category     string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	DeliveryDays uint64 `protobuf:"varint,7,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	Status       string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Gig) Reset()         { *m = Gig{} }
func (m *Gig) String() string { return proto.CompactTextString(m) }
func (*Gig) ProtoMessage()    {}
func (*Gig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eff631f6efae16b, []int{0}
}
func (m *Gig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Gig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Gig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Gig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gig.Merge(m, src)
}
func (m *Gig) XXX_Size() int {
	return m.Size()
}
func (m *Gig) XXX_DiscardUnknown() {
	xxx_messageInfo_Gig.DiscardUnknown(m)
}

var xxx_messageInfo_Gig proto.InternalMessageInfo

func (m *Gig) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Gig) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Gig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gig) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Gig) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Gig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Gig) GetDeliveryDays() uint64 {
	if m != nil {
		return m.DeliveryDays
	}
	return 0
}

func (m *Gig) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Gig) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Gig)(nil), "skillchain.marketplace.v1.Gig")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/gig.proto", fileDescriptor_6eff631f6efae16b)
}

var fileDescriptor_6eff631f6efae16b = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0xd1, 0x9a, 0x9f, 0xc1, 0x42, 0xc8, 0x20, 0x61, 0x45, 0x74, 0xc9, 0x94,
	0xa8, 0x62, 0x61, 0x05, 0x21, 0xb1, 0x67, 0x64, 0xa9, 0x8c, 0x7d, 0x15, 0xac, 0x86, 0x24, 0xb2,
	0x2f, 0x81, 0xbc, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0x4f, 0xc0, 0x1b, 0xa0, 0x3a, 0x05,
	0xc2, 0xf8, 0x9d, 0x7b, 0x3e, 0x5d, 0xe9, 0xd0, 0x85, 0x5b, 0x9b, 0x2c, 0x53, 0x8f, 0xd2, 0xe4,
	0xf1, 0x93, 0xb4, 0x6b, 0xc0, 0x32, 0x93, 0x0a, 0xe2, 0x6a, 0x19, 0xa7, 0x26, 0x8d, 0x4a, 0x5b,
	0x60, 0xc1, 0x4e, 0xff, 0x4a, 0x51, 0xaf, 0x14, 0x55, 0xcb, 0x8b, 0x2f, 0x42, 0x47, 0x77, 0x26,
	0x65, 0x47, 0x74, 0x68, 0x34, 0x27, 0x01, 0x09, 0xc7, 0xc9, 0xd0, 0x68, 0x76, 0x4c, 0x27, 0x68,
	0x30, 0x03, 0x3e, 0x0c, 0x48, 0x38, 0x4f, 0x3a, 0x60, 0x01, 0xdd, 0xd7, 0xe0, 0x94, 0x35, 0x25,
	0x9a, 0x22, 0xe7, 0x23, 0x7f, 0xeb, 0x47, 0x5b, 0xaf, 0x78, 0xc9, 0xc1, 0xf2, 0x71, 0xe7, 0x79,
	0xd8, 0xa6, 0xa5, 0x35, 0x0a, 0xf8, 0xc4, 0x3f, 0xe8, 0x80, 0x9d, 0xd1, 0x99, 0x92, 0x08, 0x69,
	0x61, 0x6b, 0x3e, 0xf5, 0xf5, 0x5f, 0x66, 0x0b, 0x7a, 0xa8, 0x21, 0x33, 0x15, 0xd8, 0x7a, 0xa5,
	0x65, 0xed, 0xf8, 0x9e, 0x37, 0x0f, 0x7e, 0xc2, 0x5b, 0x59, 0x3b, 0x76, 0x42, 0xa7, 0x0e, 0x25,
	0x3e, 0x3b, 0x3e, 0xf3, 0xfa, 0x8e, 0xd8, 0x39, 0xa5, 0xca, 0x82, 0x44, 0xd0, 0x2b, 0x89, 0x7c,
	0x1e, 0x90, 0x70, 0x94, 0xcc, 0x77, 0xc9, 0x35, 0xde, 0x5c, 0xbd, 0x37, 0x82, 0x6c, 0x1a, 0x41,
	0x3e, 0x1b, 0x41, 0xde, 0x5a, 0x31, 0xd8, 0xb4, 0x62, 0xf0, 0xd1, 0x8a, 0xc1, 0xbd, 0xe8, 0xad,
	0xf9, 0xfa, 0x6f, 0x4f, 0xac, 0x4b, 0x70, 0x0f, 0x53, 0xbf, 0xe7, 0xe5, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0xdd, 0xcd, 0x86, 0x76, 0x01, 0x00, 0x00,
}

func (m *Gig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Gig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Gig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintGig(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGig(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x42
	}
	if m.DeliveryDays != 0 {
		i = encodeVarintGig(dAtA, i, uint64(m.DeliveryDays))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintGig(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x32
	}
	if m.Price != 0 {
		i = encodeVarintGig(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGig(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGig(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGig(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintGig(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGig(dAtA []byte, offset int, v uint64) int {
	offset -= sovGig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Gig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGig(uint64(m.Id))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGig(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGig(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGig(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovGig(uint64(m.Price))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovGig(uint64(l))
	}
	if m.DeliveryDays != 0 {
		n += 1 + sovGig(uint64(m.DeliveryDays))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGig(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGig(uint64(m.CreatedAt))
	}
	return n
}

func sovGig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGig(x uint64) (n int) {
	return sovGig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Gig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Gig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Gig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliveryDays", wireType)
			}
			m.DeliveryDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeliveryDays |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGig = fmt.Errorf("proto: unexpected end of group")
)
