// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Defines the percentage fee taken by the platform on each transaction
	PlatformFeePercent uint64 `protobuf:"varint,1,opt,name=platform_fee_percent,json=platformFeePercent,proto3" json:"platform_fee_percent,omitempty"`
	// Defines the minimum contract duration in seconds
	MinContractDuration uint64 `protobuf:"varint,2,opt,name=min_contract_duration,json=minContractDuration,proto3" json:"min_contract_duration,omitempty"`
	// Defines the minimum price for creating mission
	MinGigPrice cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=min_gig_price,json=minGigPrice,proto3,customtype=cosmossdk.io/math.Int" json:"min_gig_price"`
	// Defines the duration of disputes in seconds
	DisputeDuration uint64 `protobuf:"varint,4,opt,name=dispute_duration,json=disputeDuration,proto3" json:"dispute_duration,omitempty"`
	// Defines the minimum number of arbiters required for a dispute
	MinArbitersRequired uint64 `protobuf:"varint,5,opt,name=min_arbiters_required,json=minArbitersRequired,proto3" json:"min_arbiters_required,omitempty"`
	// Defines the stake required for arbiters
	ArbiterStakeRequired uint64 `protobuf:"varint,6,opt,name=arbiter_stake_required,json=arbiterStakeRequired,proto3" json:"arbiter_stake_required,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff49d97364dd9a36, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPlatformFeePercent() uint64 {
	if m != nil {
		return m.PlatformFeePercent
	}
	return 0
}

func (m *Params) GetMinContractDuration() uint64 {
	if m != nil {
		return m.MinContractDuration
	}
	return 0
}

func (m *Params) GetDisputeDuration() uint64 {
	if m != nil {
		return m.DisputeDuration
	}
	return 0
}

func (m *Params) GetMinArbitersRequired() uint64 {
	if m != nil {
		return m.MinArbitersRequired
	}
	return 0
}

func (m *Params) GetArbiterStakeRequired() uint64 {
	if m != nil {
		return m.ArbiterStakeRequired
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "skillchain.marketplace.v1.Params")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/params.proto", fileDescriptor_ff49d97364dd9a36)
}

var fileDescriptor_ff49d97364dd9a36 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbd, 0xee, 0xd3, 0x30,
	0x14, 0xc5, 0x63, 0xfe, 0x7f, 0x2a, 0x61, 0x84, 0x80, 0xd0, 0xa2, 0xb4, 0x43, 0x52, 0x31, 0xa0,
	0x52, 0x89, 0xa4, 0x05, 0x06, 0xc4, 0x46, 0x41, 0xa0, 0x6e, 0x55, 0x61, 0x62, 0xb1, 0xdc, 0xc4,
	0x4d, 0xad, 0xc4, 0x1f, 0xd8, 0x6e, 0x05, 0x33, 0x1b, 0x13, 0x8f, 0xc0, 0xc8, 0xd8, 0x81, 0x87,
	0xe8, 0x58, 0x31, 0x21, 0x86, 0x0a, 0xb5, 0x43, 0x79, 0x0c, 0x94, 0xc4, 0xfd, 0x60, 0x60, 0xb1,
	0x7c, 0xef, 0xef, 0x1c, 0xfb, 0xd8, 0x17, 0xde, 0xd7, 0x19, 0xcd, 0xf3, 0x78, 0x86, 0x29, 0x8f,
	0x18, 0x56, 0x19, 0x31, 0x32, 0xc7, 0x31, 0x89, 0x16, 0xfd, 0x48, 0x62, 0x85, 0x99, 0x0e, 0xa5,
	0x12, 0x46, 0xb8, 0xcd, 0x93, 0x2e, 0x3c, 0xd3, 0x85, 0x8b, 0x7e, 0xeb, 0x36, 0x66, 0x94, 0x8b,
	0xa8, 0x5c, 0x2b, 0x75, 0xab, 0x19, 0x0b, 0xcd, 0x84, 0x46, 0x65, 0x15, 0x55, 0x85, 0x45, 0xf5,
	0x54, 0xa4, 0xa2, 0xea, 0x17, 0xbb, 0xaa, 0x7b, 0xef, 0xd3, 0x05, 0xac, 0x8d, 0xca, 0xfb, 0xdc,
	0x1e, 0xac, 0xcb, 0x1c, 0x9b, 0xa9, 0x50, 0x0c, 0x4d, 0x09, 0x41, 0x92, 0xa8, 0x98, 0x70, 0xe3,
	0x81, 0x36, 0xe8, 0x5c, 0x8e, 0xdd, 0x03, 0x7b, 0x45, 0xc8, 0xa8, 0x22, 0xee, 0x23, 0xd8, 0x60,
	0x94, 0xa3, 0x58, 0x70, 0xa3, 0x70, 0x6c, 0x50, 0x32, 0x57, 0xd8, 0x50, 0xc1, 0xbd, 0x2b, 0xa5,
	0xe5, 0x0e, 0xa3, 0xfc, 0x85, 0x65, 0x2f, 0x2d, 0x72, 0xdf, 0xc2, 0x1b, 0x85, 0x27, 0xa5, 0x29,
	0x92, 0x8a, 0xc6, 0xc4, 0xbb, 0x68, 0x83, 0xce, 0xb5, 0x41, 0x6f, 0xb5, 0x09, 0x9c, 0x5f, 0x9b,
	0xa0, 0x51, 0x65, 0xd6, 0x49, 0x16, 0x52, 0x11, 0x31, 0x6c, 0x66, 0xe1, 0x90, 0x9b, 0x1f, 0xdf,
	0x1f, 0x42, 0xfb, 0x98, 0x21, 0x37, 0xdf, 0xf6, 0xcb, 0x2e, 0x18, 0x5f, 0x67, 0x94, 0xbf, 0xa6,
	0xe9, 0xa8, 0x38, 0xc4, 0x7d, 0x00, 0x6f, 0x25, 0x54, 0xcb, 0xb9, 0x21, 0xa7, 0x10, 0x97, 0x65,
	0x88, 0x9b, 0xb6, 0x7f, 0x0c, 0x60, 0x43, 0x63, 0x35, 0xa1, 0x86, 0x28, 0x8d, 0x14, 0x79, 0x3f,
	0xa7, 0x8a, 0x24, 0xde, 0xd5, 0x63, 0xe8, 0xe7, 0x96, 0x8d, 0x2d, 0x72, 0x9f, 0xc0, 0xbb, 0x56,
	0x8f, 0xb4, 0xc1, 0x19, 0x39, 0x99, 0x6a, 0xa5, 0xa9, 0x6e, 0xe9, 0x9b, 0x02, 0x1e, 0x5c, 0xcf,
	0x3a, 0x7f, 0xbe, 0x06, 0xe0, 0xf3, 0x7e, 0xd9, 0x0d, 0xce, 0x66, 0xfd, 0xe1, 0x9f, 0x69, 0x57,
	0x5f, 0x3f, 0x78, 0xba, 0xda, 0xfa, 0x60, 0xbd, 0xf5, 0xc1, 0xef, 0xad, 0x0f, 0xbe, 0xec, 0x7c,
	0x67, 0xbd, 0xf3, 0x9d, 0x9f, 0x3b, 0xdf, 0x79, 0xe7, 0xff, 0xd7, 0x6a, 0x3e, 0x4a, 0xa2, 0x27,
	0xb5, 0x72, 0x8c, 0x8f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x18, 0x62, 0x64, 0x82, 0x4f, 0x02,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PlatformFeePercent != that1.PlatformFeePercent {
		return false
	}
	if this.MinContractDuration != that1.MinContractDuration {
		return false
	}
	if !this.MinGigPrice.Equal(that1.MinGigPrice) {
		return false
	}
	if this.DisputeDuration != that1.DisputeDuration {
		return false
	}
	if this.MinArbitersRequired != that1.MinArbitersRequired {
		return false
	}
	if this.ArbiterStakeRequired != that1.ArbiterStakeRequired {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ArbiterStakeRequired != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ArbiterStakeRequired))
		i--
		dAtA[i] = 0x30
	}
	if m.MinArbitersRequired != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinArbitersRequired))
		i--
		dAtA[i] = 0x28
	}
	if m.DisputeDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DisputeDuration))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.MinGigPrice.Size()
		i -= size
		if _, err := m.MinGigPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.MinContractDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinContractDuration))
		i--
		dAtA[i] = 0x10
	}
	if m.PlatformFeePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PlatformFeePercent))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PlatformFeePercent != 0 {
		n += 1 + sovParams(uint64(m.PlatformFeePercent))
	}
	if m.MinContractDuration != 0 {
		n += 1 + sovParams(uint64(m.MinContractDuration))
	}
	l = m.MinGigPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.DisputeDuration != 0 {
		n += 1 + sovParams(uint64(m.DisputeDuration))
	}
	if m.MinArbitersRequired != 0 {
		n += 1 + sovParams(uint64(m.MinArbitersRequired))
	}
	if m.ArbiterStakeRequired != 0 {
		n += 1 + sovParams(uint64(m.ArbiterStakeRequired))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformFeePercent", wireType)
			}
			m.PlatformFeePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlatformFeePercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinContractDuration", wireType)
			}
			m.MinContractDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinContractDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGigPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGigPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeDuration", wireType)
			}
			m.DisputeDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinArbitersRequired", wireType)
			}
			m.MinArbitersRequired = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinArbitersRequired |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbiterStakeRequired", wireType)
			}
			m.ArbiterStakeRequired = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ArbiterStakeRequired |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
