// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: skillchain/marketplace/v1/profile.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Profile defines the Profile message.
type Profile struct {
	Owner       string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio         string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Skills      []string `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	HourlyRate  uint64   `protobuf:"varint,5,opt,name=hourly_rate,json=hourlyRate,proto3" json:"hourly_rate,omitempty"`
	TotalJobs   uint64   `protobuf:"varint,6,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	TotalEarned uint64   `protobuf:"varint,7,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"`
	RatingSum   uint64   `protobuf:"varint,8,opt,name=rating_sum,json=ratingSum,proto3" json:"rating_sum,omitempty"`
	RatingCount uint64   `protobuf:"varint,9,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_65cc9871d900b00a, []int{0}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return m.Size()
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Profile) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Profile) GetHourlyRate() uint64 {
	if m != nil {
		return m.HourlyRate
	}
	return 0
}

func (m *Profile) GetTotalJobs() uint64 {
	if m != nil {
		return m.TotalJobs
	}
	return 0
}

func (m *Profile) GetTotalEarned() uint64 {
	if m != nil {
		return m.TotalEarned
	}
	return 0
}

func (m *Profile) GetRatingSum() uint64 {
	if m != nil {
		return m.RatingSum
	}
	return 0
}

func (m *Profile) GetRatingCount() uint64 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "skillchain.marketplace.v1.Profile")
}

func init() {
	proto.RegisterFile("skillchain/marketplace/v1/profile.proto", fileDescriptor_65cc9871d900b00a)
}

var fileDescriptor_65cc9871d900b00a = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0xeb, 0x26, 0x4d, 0x89, 0xcb, 0x80, 0x2c, 0x84, 0xcc, 0x80, 0x09, 0x2c, 0x64, 0x4a,
	0x54, 0xb1, 0x30, 0x83, 0x58, 0x98, 0x50, 0xd8, 0x58, 0x22, 0x27, 0x18, 0x1a, 0xea, 0xd8, 0x91,
	0xed, 0x14, 0xba, 0xf2, 0x04, 0x3c, 0x16, 0x63, 0x47, 0x46, 0x94, 0xbc, 0x08, 0x8a, 0x5d, 0x89,
	0xb2, 0xfd, 0xf7, 0xdd, 0xe9, 0x7e, 0xe9, 0xe0, 0x85, 0x5e, 0x56, 0x9c, 0x97, 0x0b, 0x5a, 0x89,
	0xb4, 0xa6, 0x6a, 0xc9, 0x4c, 0xc3, 0x69, 0xc9, 0xd2, 0xd5, 0x3c, 0x6d, 0x94, 0x7c, 0xae, 0x38,
	0x4b, 0x1a, 0x25, 0x8d, 0x44, 0xc7, 0x7f, 0xc1, 0x64, 0x27, 0x98, 0xac, 0xe6, 0xe7, 0x1f, 0x63,
	0x38, 0xbd, 0x77, 0x61, 0x74, 0x08, 0x27, 0xf2, 0x4d, 0x30, 0x85, 0x41, 0x04, 0xe2, 0x30, 0x73,
	0x02, 0x21, 0xe8, 0x0b, 0x5a, 0x33, 0x3c, 0xb6, 0xd0, 0xde, 0xe8, 0x00, 0x7a, 0x45, 0x25, 0xb1,
	0x67, 0xd1, 0x70, 0xa2, 0x23, 0x18, 0xd8, 0x27, 0x1a, 0xfb, 0x91, 0x17, 0x87, 0xd9, 0x56, 0xa1,
	0x53, 0x38, 0x5b, 0xc8, 0x56, 0xf1, 0x75, 0xae, 0xa8, 0x61, 0x78, 0x12, 0x81, 0xd8, 0xcf, 0xa0,
	0x43, 0x19, 0x35, 0x0c, 0x9d, 0x40, 0x68, 0xa4, 0xa1, 0x3c, 0x7f, 0x95, 0x85, 0xc6, 0x81, 0xf5,
	0x43, 0x4b, 0xee, 0x64, 0xa1, 0xd1, 0x19, 0xdc, 0x77, 0x36, 0xa3, 0x4a, 0xb0, 0x27, 0x3c, 0xb5,
	0x81, 0x99, 0x65, 0xb7, 0x16, 0x0d, 0x0d, 0x8a, 0x9a, 0x4a, 0xbc, 0xe4, 0xba, 0xad, 0xf1, 0x9e,
	0x6b, 0x70, 0xe4, 0xa1, 0xad, 0x87, 0x86, 0xad, 0x5d, 0xca, 0x56, 0x18, 0x1c, 0xba, 0x06, 0xc7,
	0x6e, 0x06, 0x74, 0x7d, 0xf5, 0xd5, 0x11, 0xb0, 0xe9, 0x08, 0xf8, 0xe9, 0x08, 0xf8, 0xec, 0xc9,
	0x68, 0xd3, 0x93, 0xd1, 0x77, 0x4f, 0x46, 0x8f, 0x64, 0x67, 0xe2, 0xf7, 0x7f, 0x23, 0x9b, 0x75,
	0xc3, 0x74, 0x11, 0xd8, 0x81, 0x2f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x3c, 0xfb, 0xa4,
	0x8b, 0x01, 0x00, 0x00,
}

func (m *Profile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Profile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Profile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RatingCount != 0 {
		i = encodeVarintProfile(dAtA, i, uint64(m.RatingCount))
		i--
		dAtA[i] = 0x48
	}
	if m.RatingSum != 0 {
		i = encodeVarintProfile(dAtA, i, uint64(m.RatingSum))
		i--
		dAtA[i] = 0x40
	}
	if m.TotalEarned != 0 {
		i = encodeVarintProfile(dAtA, i, uint64(m.TotalEarned))
		i--
		dAtA[i] = 0x38
	}
	if m.TotalJobs != 0 {
		i = encodeVarintProfile(dAtA, i, uint64(m.TotalJobs))
		i--
		dAtA[i] = 0x30
	}
	if m.HourlyRate != 0 {
		i = encodeVarintProfile(dAtA, i, uint64(m.HourlyRate))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Skills) > 0 {
		for iNdEx := len(m.Skills) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Skills[iNdEx])
			copy(dAtA[i:], m.Skills[iNdEx])
			i = encodeVarintProfile(dAtA, i, uint64(len(m.Skills[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Bio) > 0 {
		i -= len(m.Bio)
		copy(dAtA[i:], m.Bio)
		i = encodeVarintProfile(dAtA, i, uint64(len(m.Bio)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintProfile(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintProfile(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProfile(dAtA []byte, offset int, v uint64) int {
	offset -= sovProfile(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Profile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovProfile(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovProfile(uint64(l))
	}
	l = len(m.Bio)
	if l > 0 {
		n += 1 + l + sovProfile(uint64(l))
	}
	if len(m.Skills) > 0 {
		for _, s := range m.Skills {
			l = len(s)
			n += 1 + l + sovProfile(uint64(l))
		}
	}
	if m.HourlyRate != 0 {
		n += 1 + sovProfile(uint64(m.HourlyRate))
	}
	if m.TotalJobs != 0 {
		n += 1 + sovProfile(uint64(m.TotalJobs))
	}
	if m.TotalEarned != 0 {
		n += 1 + sovProfile(uint64(m.TotalEarned))
	}
	if m.RatingSum != 0 {
		n += 1 + sovProfile(uint64(m.RatingSum))
	}
	if m.RatingCount != 0 {
		n += 1 + sovProfile(uint64(m.RatingCount))
	}
	return n
}

func sovProfile(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProfile(x uint64) (n int) {
	return sovProfile(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Profile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProfile
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Profile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Profile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = append(m.Skills, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HourlyRate", wireType)
			}
			m.HourlyRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HourlyRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalJobs", wireType)
			}
			m.TotalJobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalJobs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEarned", wireType)
			}
			m.TotalEarned = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalEarned |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatingSum", wireType)
			}
			m.RatingSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RatingSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatingCount", wireType)
			}
			m.RatingCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RatingCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProfile(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProfile
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProfile(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProfile
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProfile
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProfile
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProfile
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProfile        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProfile          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProfile = fmt.Errorf("proto: unexpected end of group")
)
